"""remove usage cost field

Revision ID: adaae42d2d49
Revises: d4019c5265dc
Create Date: 2026-03-23 15:18:19.040028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adaae42d2d49"
down_revision: Union[str, Sequence[str], None] = "d4019c5265dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_logs", "total_cost_usd")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usage_logs",
        sa.Column(
            "total_cost_usd",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
